export const FETCH_BLOG_POST = 'MainLayout/FETCH_BLOG_POST';
export const FETCH_BLOG_POST_INITIATE = 'MainLayout/FETCH_BLOG_POST_INITIATE';
export const FETCH_BLOG_POST_SUCCESS = 'MainLayout/FETCH_BLOG_POST_SUCCESS';
export const FETCH_BLOG_POST_ERROR = 'MainLayout/FETCH_BLOG_POST_ERROR';
