export const FETCH_BLOG_LIST = 'MainLayout/FETCH_BLOG_LIST';
export const FETCH_BLOG_LIST_INITIATE = 'MainLayout/FETCH_BLOG_LIST_INITIATE';
export const FETCH_BLOG_LIST_SUCCESS = 'MainLayout/FETCH_BLOG_LIST_SUCCESS';
export const FETCH_BLOG_LIST_ERROR = 'MainLayout/FETCH_BLOG_LIST_ERROR';
